import { MeshStandardMaterial, DoubleSide } from 'three'
import { useGLTF } from "@react-three/drei"

export function Hooded( props ){
    const { nodes } = useGLTF( `https://customcraft.blob.core.windows.net/archivos-glb/hooded.glb` )

    const { clothingColor } = props

    const material = new MeshStandardMaterial( { color: clothingColor, side: DoubleSide } )

    return (
        <group {...props} dispose={null} scale={ 4 } >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sleeves_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sleeves_Node001.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_814930_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_814931_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_897947_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_897948_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1076031_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_274666_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1156680_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1076032_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_275632_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BindingPattern_2327953_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BindingPattern_2328040_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BindingPattern_2334657_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_3071643_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_276018_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_3071644_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_276074_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_3071645_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_276266_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pattern_3071646_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_276322_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1076033_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1156681_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_1076034_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Front_1_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Front_2_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_281708_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_281716_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855446_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855448_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855452_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855453_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855449_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_3855447_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_284077_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_284085_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_4203094_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_4203095_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_284866_Node.geometry}
                material={new MeshStandardMaterial( { color: 'grey', side: DoubleSide } )}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_284874_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Back_1_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Back_3_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Back_4_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_287136_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MatShape_287144_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Internal_Line_4946712_Node.geometry}
                material={material}
            />
            <group position={[-0.144, 1.233, 0.093]} rotation={[0.085, -0.99, 0.169]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperSlider3751887_Node.geometry}
                    material={material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperPuller4193308_Node.geometry}
                    material={material}
                    position={[0, 0, 0.003]}
                />
            </group>
            <group position={[-0.073, 1.2, 0.125]} rotation={[-0.166, -0.395, -0.289]} >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperSlider4152894_Node.geometry}
                    material={material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperPuller4192678_Node.geometry}
                    material={material}
                    position={[0, 0, 0.003]}
                />
            </group>
            <group position={[0.28, 1.446, 0.017]} rotation={[0.636, -0.667, 1.133]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperSlider4487971_Node.geometry}
                    material={material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperPuller4487992_Node.geometry}
                    material={material}
                    position={[0, 0, 0.003]}
                />
            </group>
            <group position={[-0.19, 1.221, -0.078]} rotation={[2.953, -0.573, 2.557]} >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperSlider4686650_Node.geometry}
                    material={material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ZipperPuller4747683_Node.geometry}
                    material={material}
                    position={[0, 0, 0.003]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_271999_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272103_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272206_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272317_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272421_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272436_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272587_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272691_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272794_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_272905_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273009_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273024_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273196_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273363_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273530_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273697_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_273869_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274036_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274203_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274370_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274514_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274658_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274770_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_274943_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275029_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275108_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275182_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275324_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275466_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275545_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275624_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275736_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275909_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_275995_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276066_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276094_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276114_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276162_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276210_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276258_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276314_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276342_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276362_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276410_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276458_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276506_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_276857_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277188_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277292_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277394_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277496_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277600_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277659_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_277718_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_278054_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_278385_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_278716_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_279047_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_279378_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_279709_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_280040_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_280371_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_280702_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281033_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281364_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281532_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281700_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281844_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281869_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281896_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_281997_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282021_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282144_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282173_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282199_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282223_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282257_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282281_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282315_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282389_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282458_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282577_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282759_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282782_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282805_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282924_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_282977_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283030_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283059_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283252_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283446_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283470_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283499_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283525_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283549_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283583_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283607_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283641_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283769_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283794_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283821_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283922_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_283946_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284069_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284205_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284275_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284294_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284397_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284416_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284486_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284528_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284648_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284668_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284687_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284790_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284809_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284829_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_284858_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_285210_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_285541_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_285872_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_285984_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286089_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286194_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286306_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286481_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286641_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286704_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286793_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_286968_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StitchMatShape_287128_Node.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_3751845.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_3751845_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_3751858.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_3751858_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4152852.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4152852_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4152865.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4152865_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4487929.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4487929_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4487942.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4487942_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4686608.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4686608_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4686621.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperPattern_4686621_1.geometry}
                material={material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper3751933_Node.geometry}
                material={material}
                position={[-0.145, 1.241, 0.093]}
                rotation={[0.085, -0.99, 0.169]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper3751945_Node.geometry}
                material={material}
                position={[-0.145, 1.241, 0.093]}
                rotation={[-3.102, 0.802, 2.986]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper3751966_Node.geometry}
                material={material}
                position={[-0.134, 1.06, 0.097]}
                rotation={[0.025, -0.805, 0.114]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper3751979_Node.geometry}
                material={material}
                position={[-0.134, 1.06, 0.097]}
                rotation={[3.131, 0.357, 3.084]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4152940_Node.geometry}
                material={material}
                position={[-0.07, 1.208, 0.124]}
                rotation={[-0.166, -0.395, -0.289]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4152952_Node.geometry}
                material={material}
                position={[-0.07, 1.208, 0.124]}
                rotation={[2.97, 0.41, -2.851]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4152973_Node.geometry}
                material={material}
                position={[-0.109, 1.065, 0.115]}
                rotation={[-0.077, -0.459, -0.334]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4152986_Node.geometry}
                material={material}
                position={[-0.109, 1.065, 0.115]}
                rotation={[3.088, 0.396, -2.824]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4488017_Node.geometry}
                material={material}
                position={[0.274, 1.451, 0.015]}
                rotation={[0.636, -0.667, 1.133]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4488029_Node.geometry}
                material={material}
                position={[0.274, 1.451, 0.015]}
                rotation={[-0.523, 0.227, 0.819]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4488050_Node.geometry}
                material={material}
                position={[0.361, 1.334, 0.02]}
                rotation={[0.602, -0.352, 0.404]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4488063_Node.geometry}
                material={material}
                position={[0.361, 1.334, 0.02]}
                rotation={[-2.062, 0.97, 2.498]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4686696_Node.geometry}
                material={material}
                position={[-0.193, 1.229, -0.078]}
                rotation={[2.953, -0.573, 2.557]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4686708_Node.geometry}
                material={material}
                position={[-0.193, 1.229, -0.078]}
                rotation={[2.963, -0.556, 2.843]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4686729_Node.geometry}
                material={material}
                position={[-0.136, 1.053, -0.108]}
                rotation={[2.898, -1.153, 2.598]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZipperStopper4686742_Node.geometry}
                material={material}
                position={[-0.136, 1.053, -0.108]}
                rotation={[2.889, -1.159, 2.565]}
            />
        </group>
    )
}

useGLTF.preload( `https://customcraft.blob.core.windows.net/archivos-glb/hooded.glb` )