export const GET_PRODUCTS = 'GET_PRODUCTS'
export const POST_PRODUCTS = 'POST_PRODUCTS'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE'
export const CLEAR_SEARCH_PRODUCTS = 'CLEAR_SEARCH_PRODUCTS'
export const SET_COLOR = 'SET_COLOR'
export const SET_SIZE = 'SET_SIZE'
export const SET_MODAL = 'SET_MODAL'
export const SET_DESIGN_TITLE ='SET_DESIGN_TITLE'
export const SET_DESIGN_DESCRIPTION = 'SET_DESIGN_DESCRIPTION'
export const APPLY_FILTERS = 'APPLY_FILTERS'
export const APPLY_SORTING = 'APPLY_SORTING'
export const ALL_CATEGORIES = 'ALL_CATEGORIES'
export const ADD_IMAGE = 'ADD_IMAGE'
export const CLEAR_IMAGES = 'CLEAR_IMAGES'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SET_CART_DATA = 'SET_CART_DATA'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const LOAD_CART = 'LOAD_CART';

export const GET_USERS = 'GET_USERS'; 
export const GET_USERS_BY_NAME = 'GET_USERS_BY_NAME';
export const BAN_USER = 'BAN_USER';
export const CHANGE_ROLE = 'CHANGE_ROLE';

export const GET_CART = 'GET_CART';

export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_CART_ID = 'UPDATE_CART_ID';
export const BUY_CART_ID = 'BUY_CART_ID';
export const CANCEL_CART_ID = 'CANCEL_CART_ID';
export const BUY_SUCCESS = 'BUY_SUCCESS';

export const APPLY_SORTING_TO_USERS = 'APPLY_SORTING_TO_USERS'
